### ISSUE TITLE
Alarm issue

### ISSUE THREAD

**Issue by Beingomi** [raja434/driver-fatigue-detection-system#1]
getting dis error
[INFO] loading facial landmark predictor... 
[INFO] starting video stream thread... 
Traceback (most recent call last): File "drowsiness_detection.py", line 123, in <module> if args["alarm"] != "": KeyError: 'alarm'

**Comment by dyln** [comment]
same here

**Comment by RohiniBridgitteStanly** [comment]
Getting the error 
Traceback (most recent call last): File "drowsiness_detection.py", line 123, in if args["alarm"] != "": KeyError: 'alarm'.

**Comment by RohiniBridgitteStanly** [comment]
[INFO] loading facial landmark predictor...
Getting Runtime error:
Unable to open 68 face landmarks.dat

**Comment by manmowang** [comment]
Unable to open 68 face landmarks.dat

**Comment by Beingomi** [comment]
Mail me Which file is not working properly

**Comment by mithunkr** [comment]
I got it too... 
```
Exception has occurred: KeyError
'alarm'
  File "/...../drowsiness detection.py", line 123, in <module>
    if args["alarm"] != "":
```

No resolution for it, still?

**Comment by mithunkr** [comment]
> [INFO] loading facial landmark predictor...
> Getting Runtime error:
> Unable to open 68 face landmarks.dat

I believe this is a separate issue... You should open another one for it. This issue thread is originally for another error.

**Comment by mithunkr** [comment]
> getting dis error
> [INFO] loading facial landmark predictor...
> [INFO] starting video stream thread...
> Traceback (most recent call last): File "drowsiness_detection.py", line 123, in if args["alarm"] != "": KeyError: 'alarm'

Did you get any solution for it?

**Comment by Beingomi** [comment]
whole working code will be provided to u within 500rs

**Comment by mithunkr** [comment]
Ohhh, seriously? You're selling the open-source code now?
No, Thanks!

**Comment by Praveena1809** [comment]
if args["alarm"] != "":
KeyError: 'alarm'

Any solution ?

**Comment by tanmayrsm** [comment]
Tried to solve it......hope it helps
https://github.com/tanmayrsm/drowsiness
